lib: [
  "_build/install/default/lib/OCanren/Bool.ml"
  "_build/install/default/lib/OCanren/Bool.mli"
  "_build/install/default/lib/OCanren/Core.ml"
  "_build/install/default/lib/OCanren/Core.mli"
  "_build/install/default/lib/OCanren/Disequality.ml"
  "_build/install/default/lib/OCanren/Disequality.mli"
  "_build/install/default/lib/OCanren/Env.ml"
  "_build/install/default/lib/OCanren/Env.mli"
  "_build/install/default/lib/OCanren/List.ml"
  "_build/install/default/lib/OCanren/List.mli"
  "_build/install/default/lib/OCanren/Logic.ml"
  "_build/install/default/lib/OCanren/Logic.mli"
  "_build/install/default/lib/OCanren/META"
  "_build/install/default/lib/OCanren/Nat.ml"
  "_build/install/default/lib/OCanren/Nat.mli"
  "_build/install/default/lib/OCanren/OCanren.a"
  "_build/install/default/lib/OCanren/OCanren.cma"
  "_build/install/default/lib/OCanren/OCanren.cmxa"
  "_build/install/default/lib/OCanren/OCanren.ml"
  "_build/install/default/lib/OCanren/Option.ml"
  "_build/install/default/lib/OCanren/Option.mli"
  "_build/install/default/lib/OCanren/Pair.ml"
  "_build/install/default/lib/OCanren/Pair.mli"
  "_build/install/default/lib/OCanren/Peep.ml"
  "_build/install/default/lib/OCanren/Peep.mli"
  "_build/install/default/lib/OCanren/Runconf.ml"
  "_build/install/default/lib/OCanren/Runconf.mli"
  "_build/install/default/lib/OCanren/Stream.ml"
  "_build/install/default/lib/OCanren/Stream.mli"
  "_build/install/default/lib/OCanren/Subst.ml"
  "_build/install/default/lib/OCanren/Subst.mli"
  "_build/install/default/lib/OCanren/Term.ml"
  "_build/install/default/lib/OCanren/Term.mli"
  "_build/install/default/lib/OCanren/Timer.ml"
  "_build/install/default/lib/OCanren/Timer.mli"
  "_build/install/default/lib/OCanren/dune-package"
  "_build/install/default/lib/OCanren/install_timer/install_timer.a" {"install_timer/install_timer.a"}
  "_build/install/default/lib/OCanren/install_timer/install_timer.cma" {"install_timer/install_timer.cma"}
  "_build/install/default/lib/OCanren/install_timer/install_timer.cmi" {"install_timer/install_timer.cmi"}
  "_build/install/default/lib/OCanren/install_timer/install_timer.cmt" {"install_timer/install_timer.cmt"}
  "_build/install/default/lib/OCanren/install_timer/install_timer.cmx" {"install_timer/install_timer.cmx"}
  "_build/install/default/lib/OCanren/install_timer/install_timer.cmxa" {"install_timer/install_timer.cmxa"}
  "_build/install/default/lib/OCanren/install_timer/install_timer.ml" {"install_timer/install_timer.ml"}
  "_build/install/default/lib/OCanren/oCanren.cmi"
  "_build/install/default/lib/OCanren/oCanren.cmt"
  "_build/install/default/lib/OCanren/oCanren.cmx"
  "_build/install/default/lib/OCanren/oCanren__.cmi"
  "_build/install/default/lib/OCanren/oCanren__.cmt"
  "_build/install/default/lib/OCanren/oCanren__.cmx"
  "_build/install/default/lib/OCanren/oCanren__.ml"
  "_build/install/default/lib/OCanren/oCanren__Bool.cmi"
  "_build/install/default/lib/OCanren/oCanren__Bool.cmt"
  "_build/install/default/lib/OCanren/oCanren__Bool.cmti"
  "_build/install/default/lib/OCanren/oCanren__Bool.cmx"
  "_build/install/default/lib/OCanren/oCanren__Core.cmi"
  "_build/install/default/lib/OCanren/oCanren__Core.cmt"
  "_build/install/default/lib/OCanren/oCanren__Core.cmti"
  "_build/install/default/lib/OCanren/oCanren__Core.cmx"
  "_build/install/default/lib/OCanren/oCanren__Disequality.cmi"
  "_build/install/default/lib/OCanren/oCanren__Disequality.cmt"
  "_build/install/default/lib/OCanren/oCanren__Disequality.cmti"
  "_build/install/default/lib/OCanren/oCanren__Disequality.cmx"
  "_build/install/default/lib/OCanren/oCanren__Env.cmi"
  "_build/install/default/lib/OCanren/oCanren__Env.cmt"
  "_build/install/default/lib/OCanren/oCanren__Env.cmti"
  "_build/install/default/lib/OCanren/oCanren__Env.cmx"
  "_build/install/default/lib/OCanren/oCanren__List.cmi"
  "_build/install/default/lib/OCanren/oCanren__List.cmt"
  "_build/install/default/lib/OCanren/oCanren__List.cmti"
  "_build/install/default/lib/OCanren/oCanren__List.cmx"
  "_build/install/default/lib/OCanren/oCanren__Logic.cmi"
  "_build/install/default/lib/OCanren/oCanren__Logic.cmt"
  "_build/install/default/lib/OCanren/oCanren__Logic.cmti"
  "_build/install/default/lib/OCanren/oCanren__Logic.cmx"
  "_build/install/default/lib/OCanren/oCanren__Nat.cmi"
  "_build/install/default/lib/OCanren/oCanren__Nat.cmt"
  "_build/install/default/lib/OCanren/oCanren__Nat.cmti"
  "_build/install/default/lib/OCanren/oCanren__Nat.cmx"
  "_build/install/default/lib/OCanren/oCanren__Option.cmi"
  "_build/install/default/lib/OCanren/oCanren__Option.cmt"
  "_build/install/default/lib/OCanren/oCanren__Option.cmti"
  "_build/install/default/lib/OCanren/oCanren__Option.cmx"
  "_build/install/default/lib/OCanren/oCanren__Pair.cmi"
  "_build/install/default/lib/OCanren/oCanren__Pair.cmt"
  "_build/install/default/lib/OCanren/oCanren__Pair.cmti"
  "_build/install/default/lib/OCanren/oCanren__Pair.cmx"
  "_build/install/default/lib/OCanren/oCanren__Peep.cmi"
  "_build/install/default/lib/OCanren/oCanren__Peep.cmt"
  "_build/install/default/lib/OCanren/oCanren__Peep.cmti"
  "_build/install/default/lib/OCanren/oCanren__Peep.cmx"
  "_build/install/default/lib/OCanren/oCanren__Runconf.cmi"
  "_build/install/default/lib/OCanren/oCanren__Runconf.cmt"
  "_build/install/default/lib/OCanren/oCanren__Runconf.cmti"
  "_build/install/default/lib/OCanren/oCanren__Runconf.cmx"
  "_build/install/default/lib/OCanren/oCanren__Stream.cmi"
  "_build/install/default/lib/OCanren/oCanren__Stream.cmt"
  "_build/install/default/lib/OCanren/oCanren__Stream.cmti"
  "_build/install/default/lib/OCanren/oCanren__Stream.cmx"
  "_build/install/default/lib/OCanren/oCanren__Subst.cmi"
  "_build/install/default/lib/OCanren/oCanren__Subst.cmt"
  "_build/install/default/lib/OCanren/oCanren__Subst.cmti"
  "_build/install/default/lib/OCanren/oCanren__Subst.cmx"
  "_build/install/default/lib/OCanren/oCanren__Term.cmi"
  "_build/install/default/lib/OCanren/oCanren__Term.cmt"
  "_build/install/default/lib/OCanren/oCanren__Term.cmti"
  "_build/install/default/lib/OCanren/oCanren__Term.cmx"
  "_build/install/default/lib/OCanren/oCanren__Timer.cmi"
  "_build/install/default/lib/OCanren/oCanren__Timer.cmt"
  "_build/install/default/lib/OCanren/oCanren__Timer.cmti"
  "_build/install/default/lib/OCanren/oCanren__Timer.cmx"
  "_build/install/default/lib/OCanren/opam"
  "_build/install/default/lib/OCanren/syntax/pa_ocanren.a" {"syntax/pa_ocanren.a"}
  "_build/install/default/lib/OCanren/syntax/pa_ocanren.cma" {"syntax/pa_ocanren.cma"}
  "_build/install/default/lib/OCanren/syntax/pa_ocanren.cmi" {"syntax/pa_ocanren.cmi"}
  "_build/install/default/lib/OCanren/syntax/pa_ocanren.cmt" {"syntax/pa_ocanren.cmt"}
  "_build/install/default/lib/OCanren/syntax/pa_ocanren.cmx" {"syntax/pa_ocanren.cmx"}
  "_build/install/default/lib/OCanren/syntax/pa_ocanren.cmxa" {"syntax/pa_ocanren.cmxa"}
  "_build/install/default/lib/OCanren/syntax/pa_ocanren.ml" {"syntax/pa_ocanren.ml"}
  "_build/install/default/lib/OCanren/tester/tester.a" {"tester/tester.a"}
  "_build/install/default/lib/OCanren/tester/tester.cma" {"tester/tester.cma"}
  "_build/install/default/lib/OCanren/tester/tester.cmi" {"tester/tester.cmi"}
  "_build/install/default/lib/OCanren/tester/tester.cmt" {"tester/tester.cmt"}
  "_build/install/default/lib/OCanren/tester/tester.cmti" {"tester/tester.cmti"}
  "_build/install/default/lib/OCanren/tester/tester.cmx" {"tester/tester.cmx"}
  "_build/install/default/lib/OCanren/tester/tester.cmxa" {"tester/tester.cmxa"}
  "_build/install/default/lib/OCanren/tester/tester.ml" {"tester/tester.ml"}
  "_build/install/default/lib/OCanren/tester/tester.mli" {"tester/tester.mli"}
]
libexec: [
  "_build/install/default/lib/OCanren/OCanren.cmxs"
  "_build/install/default/lib/OCanren/install_timer/install_timer.cmxs" {"install_timer/install_timer.cmxs"}
  "_build/install/default/lib/OCanren/syntax/pa_ocanren.cmxs" {"syntax/pa_ocanren.cmxs"}
  "_build/install/default/lib/OCanren/tester/tester.cmxs" {"tester/tester.cmxs"}
]
doc: [
  "_build/install/default/doc/OCanren/CHANGES"
  "_build/install/default/doc/OCanren/LICENSE"
  "_build/install/default/doc/OCanren/README.md"
]
