name: Build_PR

on:
  pull_request:
    branches:
      - 'master'

env:
  #OCANREN_STATS: yes
  OCANREN_DOCS: yes
  OPAMROOT: /home/user/.opam

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: kakadu18/ocaml:pltools
      options: --user user
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: opam update
      - name: Install dev version of GT
        run: |
          opam source GT --dev-repo
          opam pin add GT ./GT -y

      - name: Install dependencies for documentation
        run: opam install odoc pa_ppx --yes

      - run: opam install . --yes --deps-only --with-test --with-doc

      - name: List installed packages
        run: opam list

      - run: opam exec -- make #dune build
      - run: opam exec -- make test # dune runtest
